export { czmFlyTo, flyTo, getCameraPosition, getCameraRotation, getCameraTargetPos, getSceneScaleForScreenPixelSize, getSurfaceAxisClosestPoint, pickHeightPosition, pickPosition, pickVirtualEarth, } from "xbsj-xe2/dist-node/xe2-base-cesium";
export * from './angleToHumanStr';
export * from './areaToHumanStr';
export * from './createInfoPoi';
export * from './createInnerHtmlWithWhiteTextBlackBackground';
export * from './createPositionEditingRefForCzmViewer';
export * from './createPositionsEditingRefForCzmViewer';
export * from './createTilingSchema';
export * from './distanceToHumanStr';
export * from './positionToHumanStr';
export * from './CzmViewDistanceRangeControl';
export * from './d01';
export declare function getOffsetPosition(val: [number, number, number], oldVal: [number, number, number], positions: [number, number, number][]): [number, number, number][];
